"""model fix

Revision ID: 05800c195418
Revises: d8f0b39b8520
Create Date: 2024-11-12 18:26:31.855733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05800c195418'
down_revision: Union[str, None] = 'd8f0b39b8520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'Airports',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=10000),
               existing_nullable=True)
    op.add_column('wishlists', sa.Column('destination_countries', sa.String(length=10000), nullable=True))
    op.drop_column('wishlists', 'destination_airport')
    op.drop_column('wishlists', 'departure_airports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('departure_airports', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
    op.add_column('wishlists', sa.Column('destination_airport', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
    op.drop_column('wishlists', 'destination_countries')
    op.alter_column('users', 'Airports',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###
