"""empty message

Revision ID: 3c51ea548475
Revises: eb2f193ca26a
Create Date: 2024-11-14 18:42:52.624914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c51ea548475'
down_revision: Union[str, None] = 'eb2f193ca26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'is_active')
    # ### end Alembic commands ###
