"""empty message

Revision ID: 5327e51b3df4
Revises: e986d7874612
Create Date: 2024-11-12 19:43:21.360981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5327e51b3df4'
down_revision: Union[str, None] = 'e986d7874612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('destination_country', sa.String(length=1000), nullable=True))
    op.drop_column('wishlists', 'destination_countries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('destination_countries', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('wishlists', 'destination_country')
    # ### end Alembic commands ###
