"""empty message

Revision ID: 6dd7c906a143
Revises: 05800c195418
Create Date: 2024-11-12 19:21:30.141618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd7c906a143'
down_revision: Union[str, None] = '05800c195418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlists', 'destination_countries',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlists', 'destination_countries',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)
    # ### end Alembic commands ###
