"""Add is_superuser field to admin_users

Revision ID: ef5443454b0b
Revises: d0eecc3e4492
Create Date: 2024-11-14 18:33:50.353240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5443454b0b'
down_revision: Union[str, None] = 'd0eecc3e4492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'is_superuser')
    # ### end Alembic commands ###
