"""Rename column example

Revision ID: fe59b3b79dd4
Revises: 
Create Date: 2024-11-12 17:36:43.774666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe59b3b79dd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from alembic import op

# Переименовываем колонку в таблице 'users' с 'Name' на 'FullName'
    op.alter_column('wishlists', 'DestinationCity', new_column_name='destination_countries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
